server:
  port: 8014
spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://home.mytest.com:3306/cloud_account?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: home.mytest.com:8848
        log-name: ${spring.application.name}
    sentinel:
      transport:
        dashboard: home.mytest.com:8858
      eager: true
      datasource:
        # 对外部接口调用配置限流规则
        ds1:
          nacos:
            server-addr: home.mytest.com:8848
            data-id: ${spring.application.name}-sentinel
            group-id: DEFAULT_GROUP
            rule-type: flow
  profiles:
    include: dev,seata
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    # 在控制台打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#mybatis:
  # config-location 和 configuration不能同时定义
#  config-location: classpath:mybatis/mybatis-config.xml
#  type-aliases-package: com.zsj.account.mybatis.mapper
#  mapper-locations: classpath:mybatis/mapper/*.xml
#  configuration:
#    # 在控制台打印日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  path: "D:\\workspace-Java\\my_project\\springCloudTest\\logs\\account"
  level:
    # 打印SQL
    com.zsj.account.mybatis.mapper: debug
