server:
  port: 8012
spring:
  application:
    name: orders-service
  cloud:
    nacos:
      discovery:
        server-addr: home.mytest.com:8848
        log-name: ${spring.application.name}
    sentinel:
      transport:
        dashboard: home.mytest.com:8858
#      # 取消延迟加载
      eager: true
#      # 持久化设置, sentinel会自动到Nacos中去读取配置信息
      datasource:
        # 对外部接口调用配置限流规则
        ds1:
          nacos:
            server-addr: home.mytest.com:8848
            data-id: ${spring.application.name}-sentinel
#            namespace: 0c859740-03c4-4c76-bda8-36d7c09db1ee
            group-id: DEFAULT_GROUP
            rule-type: flow
        # 对访问的接口配置降级规则
        ds2:
          nacos:
            server-addr: home.mytest.com:8848
            data-id: ${spring.application.name}-degrade
            group-id: DEFAULT_GROUP
#            namespace: 0c859740-03c4-4c76-bda8-36d7c09db1ee
            rule-type: degrade
#    alibaba:
#      seata:
        #是服务组名称，与nacos-handler.txt 配置的service.vgroup_mapping.${your-service-gruop}具有对应关系
        # 该配置转到 application-seata.yml中tx-service-group: ${spring.application.name}-tx-service-group
  datasource:
    url: jdbc:mysql://home.mytest.com:3306/cloud_orders
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    include: seata
    #mybatis:
  # handler-location 和 configuration不能同时定义
  #  handler-location: classpath:mybatis/mybatis-handler.xml
    #  type-aliases-package: com.zsj.orders.mybatis.mapper
#  mapper-locations: classpath:mybatis/mapper/*.xml
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    # 在控制台打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  path: "D:\\workspace-Java\\my_project\\springCloudTest\\logs\\orders"
  level:
    # 打印SQL
    com.zsj.account.mybatis.mapper: debug
feign:
  sentinel:
    enabled: true
#  client:
#    handler:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: basic
