server:
  port: 8010
spring:
  application:
    name: common-service
  cloud:
    nacos:
      discovery:
        server-addr: home.mytest.com:8848
        log-name: ${spring.application.name}
    sentinel:
      transport:
        dashboard: home.mytest.com:8858
      # 取消延迟加载
      eager: true
      # 持久化设置, sentinel会自动到Nacos中去读取配置信息
      datasource:
        ds1:
          nacos:
            server-addr: home.mytest.com:8848
            data-id: ${spring.application.name}-sentinel
            group-id: DEFAULT_GROUP
            rule-type: flow
  datasource:
    url: jdbc:mysql://home.mytest.com:3306/cloud_common
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: home.mytest.com
    password: 123456
    database: 9
    jedis:
      pool:
        max-active: 5
        max-idle: 3
  profiles:
    include: seata,custom-config,swagger
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    # 在控制台打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  path: "D:\\workspace-Java\\my_project\\springCloudTest\\logs\\common"
  level:
    # 打印SQL
    com.zsj.account.mybatis.mapper: debug
  # 怎么没有生效
  file:
    max-size: 1MB
    max-history: 20